#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

FROM docker.io/library/maven:3-eclipse-temurin-21 AS build

COPY src /root/src
COPY pom.xml /root/pom.xml

WORKDIR /root
RUN mvn package

FROM eclipse-temurin:21 AS run

RUN useradd -r fritz
USER fritz

COPY --from=build --chown=fritz:root /root/target/quarkus-app /home/fritz/quarkus-app

ENTRYPOINT ["java", "-jar", "/home/fritz/quarkus-app/quarkus-run.jar"]
